### ISSUE TITLE
Please do not commit EWU pem or cert files on a public repo

### ISSUE THREAD

**Issue by CountryNerd** [ashermancinelli/ape#22]
https://github.com/ashermancinelli/ape/blob/b2e69b559fffd2780eb9c9ef6676d1046b2765f3/ape/sso/comodo_combo.pem#L1

**Comment by chazhurd** [comment]
Tried to make my repo private, but unable to do so as its a fork from a public repo. @ashermancinelli Maybe we can make this main repo private and invite collaborators?

**Comment by ashermancinelli** [comment]
Thanks! If there are any other sensitive files we should not have private, comment and I will take care of it.
